# Generated by Django 5.2.7 on 2025-11-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_notes'),
    ]

    operations = [
        
    ]
