# Generated by Django 5.2.7 on 2025-11-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20251125_1432'),
    ]

    operations = [
    ]
